In [2]:
# Tensor practice
# similar to ndarray and numpy arrays
import torch
import numpy as np

# initialize a tensor
data = [[1,2], [3,4]]
x_data = torch.tensor(data)
print(x_data)

# from numpy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]])


In [3]:
# tensor from tensor
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(x_ones)

x_rand = torch.rand_like(x_data, dtype=)

tensor([[1, 1],
        [1, 1]])
